$gep_between_submaps =   
$back_exit_submaps=$gep_between_submaps│$gep_between_submaps( 󱞳 )Back$gep_between_submaps( 󱊷 )Exit
$back_only_submaps=$gep_between_submaps│$gep_between_submaps( 󱊷 )Exit

# all window submaps
source = windows/main.conf
#
# all apps submaps
source = apps/main.conf
#
# all prefix submaps
source = prefix/main.conf
#
# all tabs submaps
source = tabs/main.conf

# all cursor submaps
# source = cursor/main.conf

