thm_bg="#1e1e2e"
thm_fg="#cdd6f4"
thm_cyan="#89dceb"
set -g @catppuccin_status_fill "icon"
thm_black="#181825"
thm_gray="#313244"
thm_magenta="#cba6f7"
thm_pink="#f5c2e7"
thm_red="#f38ba8"
thm_green="#a6e3a1"
thm_yellow="#f9e2af"
thm_blue="#89b4fa"
thm_orange="#fab387"
thm_black4="#585b70"

set -g @plugin 'omerxx/catppuccin-tmux' # commented this because of all the feature i dumpped here, now this can run without plugin

# separators
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_left_separator ""

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_middle_separator  "█"
set -g @catppuccin_status_right_separator ""

# modules
set -g @catppuccin_status_modules_left ""
set -g @catppuccin_status_modules_right "directory application session"

# status
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_connect_separator "no"
# set -g @catppuccin_status_right_separator_inverse "no"
# set -g @catppuccin_status_fill "icon"

# # window
set -g @catppuccin_icon_window_last "󰁯 "
set -g @catppuccin_icon_window_current "󱓻 "
set -g @catppuccin_icon_window_zoom "󰁌 "
set -g @catppuccin_icon_window_mark "󰃀 "
set -g @catppuccin_icon_window_silent "󰂛 "
set -g @catppuccin_icon_window_activity "󰖲 "
set -g @catppuccin_icon_window_bell "󰂞 "

set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_current_text "#W"
# set -g @catppuccin_window_current_text "#{pane_current_path}"
# set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag, 󰁌  ,}"
set -g @catppuccin_window_default_text "#W"
# set -g @catppuccin_window_default_text "#{pane_current_path}"
# set -g @catppuccin_window_default_text "#W#{?window_zoomed_flag, 󰁌  ,}"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_user_color "$thm_magenta"

set -g @catppuccin_window_status_icon_enable "no"
set -g @catppuccin_window_status_enable "no"

# set -g @catppuccin_window_current_format_directory_text "#{b:pane_current_path}"


# application
set -g @catppuccin_application_icon "󰀻"
set -g @catppuccin_application_color "$thm_yellow"
set -g @catppuccin_application_text "#W"

# user
set -g @catppuccin_user_icon ""
set -g @catppuccin_user_color "$thm_magenta"
set -g @catppuccin_user_text "#(whoami)"

# session
set -g @catppuccin_session_icon ""
set -g @catppuccin_session_color "#{?client_prefix,$thm_red,$thm_green}"
set -g @catppuccin_session_text "#S"

# host
set -g @catppuccin_host_icon "󰒋"
set -g @catppuccin_host_color "$thm_magenta"
set -g @catppuccin_host_text "#H"

# directory
set -g @catppuccin_directory_icon ""
set -g @catppuccin_directory_color "$thm_pink"
# set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_directory_text "#(echo '#{pane_current_path}' | sed 's|^$HOME|~|')"

# date and time
set -g @catppuccin_date_time_icon  "󰥔"
set -g @catppuccin_date_time_color "$thm_cyan"
set -g @catppuccin_date_time_text "%r"

# battery
set -g @batt_icon_charge_tier8 '󰁹'
set -g @batt_icon_charge_tier7 '󰂁'
set -g @batt_icon_charge_tier6 '󰁿'
set -g @batt_icon_charge_tier5 '󰁾'
set -g @batt_icon_charge_tier4 '󰁽'
set -g @batt_icon_charge_tier3 '󰁼'
set -g @batt_icon_charge_tier2 '󰁻'
set -g @batt_icon_charge_tier1 '󰁺'
set -g @batt_icon_status_charged '󰚥'
set -g @batt_icon_status_charging '󰂄'
set -g @batt_icon_status_discharging '󰂃'
set -g @batt_icon_status_unknown '󰂑'

set -g @catppuccin_battery_icon "#{battery_icon}"
set -g @catppuccin_battery_color "$thm_yellow"
set -g @catppuccin_battery_text "#{battery_percentage}"

